### ISSUE TITLE
Sharing a local development project publically (hgrok)

### ISSUE THREAD

**Issue by dsandip** [hasura/content#6]

**Comment by mokshagna517** [comment]
I downloaded hgrok in my ubuntu 17.04 os
Then I opened it with apturl.But is not being installed.It is showing an error.The error is no ':'  in the url
Please help me

**Comment by arvi3411301** [comment]
You need to Run chmod +x hgrok && sudo mv hgrok /usr/local/bin/

--
Aravind Shankar
+91-9884682026

**Comment by mokshagna517** [comment]
It is saying so such file or directory hgrok
It is actually ngrok_linux_amd64 that I downloaded

**Comment by arvi3411301** [comment]
Rename it to hgrok and execute the command I gave.

**Comment by mokshagna517** [comment]
This is what I am getting
![screenshot from 2017-06-07 16-27-28](https://user-images.githubusercontent.com/22216655/26875174-30a9fcf2-4b70-11e7-8168-d06f4e9db720.png)

**Comment by mokshagna517** [comment]
I renamed and executed this command.I started minikube in another terminal .

**Comment by arvi3411301** [comment]
You need your minikube machine to be up and running,

**Comment by mokshagna517** [comment]
It is running now and I am also able to log in my console

**Comment by arvi3411301** [comment]
Since you have moved hgrok to your BIN PATH, you need to execute with
sudo hgrok and not sudo ./hgrok

**Comment by mokshagna517** [comment]
Thankyou .
![screenshot from 2017-06-07 16-49-32](https://user-images.githubusercontent.com/22216655/26875851-39d00134-4b73-11e7-8e1d-a75c98af32fd.png)
